#!/usr/bin/env sh
set -e

# ================================================================================
if ! test -d '.git'; then
	echo 'error: not a git repo' >&2
	exit 1
fi

git config --local blame.ignoreRevsFile .git-blame-ignore-revs
ln -srf scripts/check .git/hooks/pre-commit
printf '\033[1;32mdone\n'
